# Generated by Django 4.2 on 2026-01-31 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0016_delete_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_threshold', models.FloatField(default=0.6, help_text='Cosine similarity threshold for face recognition (0.0-1.0). Higher = stricter matching.')),
            ],
            options={
                'verbose_name': 'Recognition Settings',
                'verbose_name_plural': 'Recognition Settings',
            },
        ),
        migrations.AddField(
            model_name='face',
            name='embedding',
            field=models.BinaryField(blank=True, help_text='512-dim FaceNet embedding', null=True),
        ),
    ]
