# Generated by Django 4.2 on 2026-02-13 22:28

import camera.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0017_recognitionsettings_face_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='smtp_password',
            field=camera.encryption.EncryptedCharField(max_length=500),
        ),
    ]
